version: '3'

services:
    app:
      build:
        context: .
      container_name: app
      ports:
        - "${API_PORT:-8080}:${API_PORT:-8080}"
      restart: unless-stopped
      volumes:
            - ./data:/data

