version: '3'

services:
    ponto:
      build:
        context: .
      container_name: ponto
      ports:
        - "${API_PORT:-8080}:${API_PORT:-8080}"
      restart: unless-stopped
      volumes:
            - ./data:/data

